
-- File Name       : CDUSRP (Table)
-- Author          : Subu
-- Date            : 02/11/2024
-- Description     : Users Master

CREATE OR REPLACE TABLE CARDDEMO1/CDUSRP (
USERID CHAR(10) CCSID 37 NOT NULL DEFAULT '' ,
FIRSTNAME VARCHAR(20) NOT NULL WITH DEFAULT ,
LASTNAME VARCHAR(20) NOT NULL ,
TYPE CHAR(1) CCSID 37 NOT NULL DEFAULT 'I',
EMAIL VARCHAR(50) NOT NULL DEFAULT '' ,
STATUS CHAR(1) CCSID 37 NOT NULL,
USRCRTDT DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
USRCRTTM DECIMAL(6, 0) NOT NULL DEFAULT 0 ,
USRCRTUSR CHAR(10) NOT NULL DEFAULT '' ,
USRCRTPGM CHAR(10) NOT NULL DEFAULT '' ,
USRCHGDT DECIMAL(7, 0) NOT NULL DEFAULT 0 ,
USRCHGTM DECIMAL(6, 0) NOT NULL DEFAULT 0 ,
USRCHGUSR CHAR(10) NOT NULL DEFAULT '' ,
USRCHGPGM CHAR(10) NOT NULL DEFAULT '' )
PARTITION BY HASH (USERID) INTO 2 PARTITIONS
RCDFMT CDUSRPR ;

LABEL ON TABLE CDUSRP
IS 'CardDemo - Users (SQL)' ;

LABEL ON COLUMN CDUSRP
(USERID TEXT IS 'USER ID' ,
FIRSTNAME TEXT IS 'FIRST NAME' ,
LASTNAME TEXT IS 'LAST NAME' ,
TYPE TEXT IS 'USER TYPE' ,
USRCRTDT TEXT IS 'TRN ADD DATE' ,
USRCRTTM TEXT IS 'TRN ADD TIME' ,
USRCRTUSR TEXT IS 'TRN ADD USER' ,
USRCRTPGM TEXT IS 'TRN ADD PROGRAM' ,
USRCHGDT TEXT IS 'TRN CHANGE DATE' ,
USRCHGTM TEXT IS 'TRN CHANGE TIME' ,
USRCHGUSR TEXT IS 'TRN CHANGE USER' ,
USRCHGPGM TEXT IS 'TRN CHANGE PROGRAM' ) ;

